steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/api-for-warp-drive/lucy-webhook', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/api-for-warp-drive/lucy-webhook']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'lucy-webhook'
  - '--image'
  - 'gcr.io/api-for-warp-drive/lucy-webhook'
  - '--region'
  - 'us-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
substitutions:
  _REGION: us-west1
  _SERVICE: lucy-webhook