apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lucy-webhook
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: gcr.io/api-for-warp-drive/lucy-webhook
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "96300Mi"
            cpu: "4"
          requests:
            memory: "96300Mi"
            cpu: "2"
        env:
        - name: PORT
          value: "8080"