apiVersion: v1
kind: ConfigMap
metadata:
  name: port-allocations
data:
  lucy-webhook: "8080"
  ray-head: "10001"
  ray-workers: "10002-10010"
  vertex-endpoints: "8000-8010"
  vision-lake: "9090"
  notebooks: "8888"
  monitoring: "9091"
  metrics: "9093"
  healthcheck: "8081"
  ingress: "80,443"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: port-control
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
    - port: 443
      protocol: TCP