apiVersion: monitoring.googleapis.com/v1
kind: AlertPolicy
metadata:
  name: port-monitoring
spec:
  conditions:
  - displayName: Port Connectivity
    conditionThreshold:
      filter: metric.type="istio.io/service/server/response_latencies" resource.type="k8s_container"
      aggregations:
      - alignmentPeriod: 60s
        crossSeriesReducer: REDUCE_COUNT
        perSeriesAligner: ALIGN_DELTA
      comparison: COMPARISON_GT
      duration: 60s
      trigger:
        count: 1
  - displayName: Port Binding
    conditionThreshold:
      filter: metric.type="kubernetes.io/container/port_bind_errors"
      comparison: COMPARISON_GT
      threshold: 0
      duration: 0s
  combiner: OR
  alertStrategy:
    autoClose: 1800s
  notification_channels:
  - name: projects/api-for-warp-drive/notificationChannels/email
  - name: projects/api-for-warp-drive/notificationChannels/slack